name: Trigger auto deployment for faizal-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/faizal-container-app-AutoDeployTrigger-dce324b0-0cdf-49ca-b0f6-55db353a9e20.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FAIZALCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: acrfaizal.azurecr.io
          registryUsername: ${{ secrets.FAIZALCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FAIZALCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: faizal-container-app
          resourceGroup: rg-my-container-apps
          imageToBuild: acrfaizal.azurecr.io/faizal-container-app:${{ github.sha }}
          
            

     

